when:  
  branch: [main]
  event: [push, pull_request]

# clone:
#   git:
#     image: woodpeckerci/plugin-git

steps:

  - name: "build"
    image: steckschwein/buildenv:alpine_321
    commands:
      - make 
    when:
      event: [pull_request, push]

  - name: "unit tests"
    image: steckschwein/buildenv:alpine_321
    commands:
      - make test
    when:
      event: [pull_request, push]
