when:  
  branch: [main]
  event: [push, pull_request]

# clone:
#   git:
#     image: woodpeckerci/plugin-git

steps:
  - name: "build"
    image: steckschwein/buildenv:ubuntu_24.04
    commands:
      - make 
      - make test
    when:
      event: [pull_request, push]
