when:  
  branch: [main]
  event: [push, pull_request]

# clone:
#   git:
#     image: woodpeckerci/plugin-git

steps:
  - name: "build asmunit"
    image: steckschwein/buildenv:cc65_2_20-snapshot
    commands:
      - cd asmunit
      - make
    when:
      event: [pull_request, push]

  - name: "build steckos"
    image: steckschwein/buildenv:cc65_2_20-snapshot
    commands:
      - cd steckos/kernel
      - make 
    when:
      event: [pull_request, push]

  - name: "test"
    image: steckschwein/buildenv:cc65_2_20-snapshot
    commands:
      - cd steckos/kernel/test
      - make
    when:
      event: [pull_request, push]

  - name: "mail"
    image: deblan/woodpecker-email
    settings:
       level: failure
       recipients:
        - info@steckschwein.de
    when:
      status:
        - success