when:  
  branch: [main]
  event: [push, pull_request]

clone:
  git:
    image: woodpeckerci/plugin-git

steps:
  - name: "build"
    image: steckschwein/buildenv:cc65_2_20-snapshot
    commands:
      - cd asmunit
      - make
      - cd steckos/kernel
      - make 
    when:
      event: [pull_request, push]

  - name: "test"
    image: steckschwein/buildenv:cc65_2_20-snapshot
    commands:
      - cd steckos/kernel/test
      - make
    when:
      event: [pull_request, push]
